### ISSUE TITLE
Drop faulty lines before caching

### ISSUE THREAD

**Issue by GGDRriedel** [Oi-sin/ddmovebis#1]
"
        #some lines don't contain correct coordinates -> remove
        chunked_df.drop(chunked_df[chunked_df.geometry == 'LINESTRING EMPTY'].index, inplace=True)
"

IMO this should be before writing to cache

**Comment by Oi-sin** [comment]
Thank you for your report. 

In the original data there are no empty lines. The entries with `'LINESTRING EMPTY'` seem to get introduced by the `to_crs()` call. This was just a quick way to work around this issue that I don't fully understand. I'll try to get a better understanding of what is going wrong.

**Comment by Oi-sin** [comment]
I found the source of those `LINESTRING EMPTY` entries in the GeoDataFrame. They are created by the 'gdp.clip()' function. This seems to be a bug in the library. The clipping does not work for lines that have identical latitude.

Sample Code:
```python
data = {'geometry':  ['LINESTRING (13.69240 51.06939, 13.69257 51.06939)']}
df = pd.DataFrame (data, columns = ['geometry'])
df['geometry'] = df['geometry'].apply(wkt.loads)
gdf = gpd.GeoDataFrame(df, geometry='geometry', crs=source_crs)
print(gdf)
clipped_gdf = gpd.clip(gdf, poly_municipality)
print(clipped_gdf)

data = {'geometry':  ['LINESTRING (13.69240 51.06938, 13.69257 51.06939)']}
df = pd.DataFrame (data, columns = ['geometry'])
df['geometry'] = df['geometry'].apply(wkt.loads)
gdf = gpd.GeoDataFrame(df, geometry='geometry', crs=source_crs)
print(gdf)
clipped_gdf = gpd.clip(gdf, poly_municipality)
print(clipped_gdf)
```
outputs:
```console
                                            geometry
0  LINESTRING (13.69240 51.06939, 13.69257 51.06939)
           geometry
0  LINESTRING EMPTY
                                            geometry
0  LINESTRING (13.69240 51.06938, 13.69257 51.06939)
                                            geometry
0  LINESTRING (13.69240 51.06938, 13.69257 51.06939)
```

**Comment by Oi-sin** [comment]
This really seems to be a bug in the clip function of geopandas. I have filed a bug report https://github.com/geopandas/geopandas/issues/1841 with sample code.
